version: "3.8"
services:

  user-service-app:
    container_name: user_service
    build: .

    ports:
      - "8080:8080"

    depends_on:
      - user-mongodb-db

    restart: always

  user-mongodb-db:
    container_name: user-mongodb-db
    image: mongo
    restart: always
    ports:
      - "27017:27017"

    volumes:
      - socialnetwork-volume:/var/lib/user-mongodb

volumes:
  socialnetwork-volume:


